/Users/newpooter/GitHub/zammad-1.5.0/app/models/scheduler.rb:114:in `rescue in _start_job': STOP thread for Ticket.process_auto_unassign after 10 tries (RuntimeError)
	from /Users/newpooter/GitHub/zammad-1.5.0/app/models/scheduler.rb:86:in `_start_job'
	from /Users/newpooter/GitHub/zammad-1.5.0/app/models/scheduler.rb:112:in `rescue in _start_job'
	from /Users/newpooter/GitHub/zammad-1.5.0/app/models/scheduler.rb:86:in `_start_job'
	from /Users/newpooter/GitHub/zammad-1.5.0/app/models/scheduler.rb:112:in `rescue in _start_job'
	from /Users/newpooter/GitHub/zammad-1.5.0/app/models/scheduler.rb:86:in `_start_job'
	from /Users/newpooter/GitHub/zammad-1.5.0/app/models/scheduler.rb:112:in `rescue in _start_job'
	from /Users/newpooter/GitHub/zammad-1.5.0/app/models/scheduler.rb:86:in `_start_job'
	from /Users/newpooter/GitHub/zammad-1.5.0/app/models/scheduler.rb:112:in `rescue in _start_job'
	from /Users/newpooter/GitHub/zammad-1.5.0/app/models/scheduler.rb:86:in `_start_job'
	from /Users/newpooter/GitHub/zammad-1.5.0/app/models/scheduler.rb:112:in `rescue in _start_job'
	from /Users/newpooter/GitHub/zammad-1.5.0/app/models/scheduler.rb:86:in `_start_job'
	from /Users/newpooter/GitHub/zammad-1.5.0/app/models/scheduler.rb:112:in `rescue in _start_job'
	from /Users/newpooter/GitHub/zammad-1.5.0/app/models/scheduler.rb:86:in `_start_job'
	from /Users/newpooter/GitHub/zammad-1.5.0/app/models/scheduler.rb:112:in `rescue in _start_job'
	from /Users/newpooter/GitHub/zammad-1.5.0/app/models/scheduler.rb:86:in `_start_job'
	from /Users/newpooter/GitHub/zammad-1.5.0/app/models/scheduler.rb:112:in `rescue in _start_job'
	from /Users/newpooter/GitHub/zammad-1.5.0/app/models/scheduler.rb:86:in `_start_job'
	from /Users/newpooter/GitHub/zammad-1.5.0/app/models/scheduler.rb:112:in `rescue in _start_job'
	from /Users/newpooter/GitHub/zammad-1.5.0/app/models/scheduler.rb:86:in `_start_job'
	from /Users/newpooter/GitHub/zammad-1.5.0/app/models/scheduler.rb:73:in `block in start_job'
